/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ringcentral.hello.world;

import com.ringcentral.RestException;
import java.io.IOException;
import com.ringcentral.definitions.GetExtensionInfoResponse;
import com.ringcentral.RestClient;
public class App {
    public String getExtensionNumber() throws IOException, RestException {
        RestClient rc = new RestClient(
            System.getenv("RINGCENTRAL_CLIENT_ID"),
            System.getenv("RINGCENTRAL_CLIENT_SECRET"),
            System.getenv("RINGCENTRAL_SERVER_URL")
        );
rc.authorize(
            System.getenv("RINGCENTRAL_USERNAME"),
            System.getenv("RINGCENTRAL_EXTENSION"),
            System.getenv("RINGCENTRAL_PASSWORD")
        );
        GetExtensionInfoResponse extensionInfo = rc.restapi().account().extension().get();
        rc.revoke();
        return extensionInfo.extensionNumber;
    }
    public static void main(String[] args) throws IOException, RestException {
        System.out.println(new App().getExtensionNumber());
    }
}
